import type { FaceFilterCategory, FaceFilterDef, FaceFilterId } from './types';

export const FILTER_CATEGORIES: { id: FaceFilterCategory; label: string }[] = [
  { id: 'trending', label: 'Trending' },
  { id: 'backgrounds', label: 'Background' },
  { id: 'privacy', label: 'Privacy' },
  { id: 'glasses', label: 'Glasses' },
  { id: 'funny', label: 'Funny' },
  { id: 'beauty', label: 'Beauty' },
  { id: 'animals', label: 'Animals' },
  { id: 'masks', label: 'Masks' },
];

/** Landmark-locked original filters. Add a catalog row — do not change the tracker. */
export const FACE_FILTER_CATALOG: FaceFilterDef[] = [
  { id: 'none', name: 'Off', category: 'trending', emoji: '✕', scale: 1 },
  {
    id: 'blackSunglasses',
    name: 'Black Sunglasses',
    category: 'glasses',
    emoji: '🕶️',
    scale: 1.28,
    anchor: 'eyes',
    layers: [{ kind: 'sunglasses', anchor: 'eyes', scale: 1.28 }],
  },
  {
    id: 'aviatorSunglasses',
    name: 'Aviator Sunglasses',
    category: 'glasses',
    emoji: '😎',
    scale: 1.32,
    anchor: 'eyes',
    layers: [{ kind: 'aviator', anchor: 'eyes', scale: 1.32 }],
  },
  {
    id: 'heartGlasses',
    name: 'Heart Glasses',
    category: 'glasses',
    emoji: '😍',
    scale: 1.28,
    anchor: 'eyes',
    layers: [{ kind: 'heartGlasses', anchor: 'eyes', scale: 1.28 }],
  },
  {
    id: 'rainbowGlasses',
    name: 'Rainbow Glasses',
    category: 'glasses',
    emoji: '🌈',
    scale: 1.26,
    yOffset: -0.02,
    anchor: 'eyes',
    layers: [{ kind: 'rainbowGlasses', anchor: 'eyes', scale: 1.26, yOffset: -0.02 }],
  },
  {
    id: 'animeEyes',
    name: 'Anime Eyes',
    category: 'glasses',
    emoji: '👀',
    scale: 1.18,
    anchor: 'eyes',
    layers: [{ kind: 'animeEyes', anchor: 'eyes', scale: 1.18 }],
  },
  {
    id: 'laserEyes',
    name: 'Laser Eyes',
    category: 'funny',
    emoji: '🔴',
    scale: 1.2,
    anchor: 'eyes',
    layers: [{ kind: 'laserEyes', anchor: 'eyes', scale: 1.2 }],
  },
  {
    id: 'medicalMask',
    name: 'Medical Mask',
    category: 'masks',
    emoji: '😷',
    scale: 1.35,
    anchor: 'mouth',
    layers: [{ kind: 'medicalMask', anchor: 'mouth', scale: 1.35 }],
  },
  {
    id: 'anonymousMask',
    name: 'Anonymous Mask',
    category: 'privacy',
    emoji: '🎭',
    scale: 1.2,
    privacy: 'solid',
    anchor: 'face',
    layers: [{ kind: 'anonMask', anchor: 'face', scale: 1.18 }],
  },
  { id: 'pixelFace', name: 'Pixel Face', category: 'privacy', emoji: '🟦', scale: 1.18, privacy: 'pixel', anchor: 'face' },
  { id: 'mosaicFace', name: 'Mosaic Face', category: 'privacy', emoji: '🧩', scale: 1.18, privacy: 'mosaic', anchor: 'face' },
  { id: 'blurFace', name: 'Blur Face', category: 'privacy', emoji: '🌫️', scale: 1.18, privacy: 'blur', anchor: 'face' },
  {
    id: 'fakeMustache',
    name: 'Fake Mustache',
    category: 'funny',
    emoji: '🥸',
    scale: 1.22,
    anchor: 'mouth',
    layers: [{ kind: 'mustache', anchor: 'mouth', scale: 1.22, yOffset: -0.04 }],
  },
  {
    id: 'clownNose',
    name: 'Clown Nose',
    category: 'funny',
    emoji: '🤡',
    scale: 0.95,
    anchor: 'nose',
    layers: [{ kind: 'clownNose', anchor: 'nose', scale: 0.95 }],
  },
  {
    id: 'robotFace',
    name: 'Robot Face',
    category: 'masks',
    emoji: '🤖',
    scale: 1.2,
    anchor: 'face',
    layers: [
      { kind: 'robotVisor', anchor: 'eyes', scale: 1.2 },
      { kind: 'robotJaw', anchor: 'mouth', scale: 1.05 },
    ],
  },
  {
    id: 'catFace',
    name: 'Cat Face',
    category: 'animals',
    emoji: '🐱',
    scale: 1.22,
    anchor: 'face',
    layers: [
      { kind: 'catEars', anchor: 'forehead', scale: 1.28, yOffset: -0.06 },
      { kind: 'catNose', anchor: 'nose', scale: 0.85 },
      { kind: 'catWhiskers', anchor: 'mouth', scale: 1.15, yOffset: -0.08 },
    ],
  },
  {
    id: 'dogFace',
    name: 'Dog Face',
    category: 'animals',
    emoji: '🐶',
    scale: 1.22,
    anchor: 'face',
    layers: [
      { kind: 'dogEars', anchor: 'forehead', scale: 1.32, yOffset: -0.04 },
      { kind: 'dogNose', anchor: 'nose', scale: 0.92 },
    ],
  },
  {
    id: 'bunnyEars',
    name: 'Bunny Ears',
    category: 'animals',
    emoji: '🐰',
    scale: 1.35,
    yOffset: -0.08,
    anchor: 'forehead',
    layers: [{ kind: 'bunnyEars', anchor: 'forehead', scale: 1.35, yOffset: -0.08 }],
  },
  {
    id: 'crown',
    name: 'Crown',
    category: 'trending',
    emoji: '👑',
    scale: 1.38,
    yOffset: -0.1,
    anchor: 'forehead',
    layers: [{ kind: 'crown', anchor: 'forehead', scale: 1.38, yOffset: -0.1 }],
  },
  {
    id: 'flowerCrown',
    name: 'Flower Crown',
    category: 'trending',
    emoji: '🌸',
    scale: 1.4,
    yOffset: -0.08,
    anchor: 'forehead',
    layers: [{ kind: 'flowerCrown', anchor: 'forehead', scale: 1.4, yOffset: -0.08 }],
  },
  {
    id: 'devilHorns',
    name: 'Devil Horns',
    category: 'funny',
    emoji: '😈',
    scale: 1.32,
    yOffset: -0.1,
    anchor: 'forehead',
    layers: [{ kind: 'devilHorns', anchor: 'forehead', scale: 1.32, yOffset: -0.1 }],
  },
  { id: 'smoothSkin', name: 'Smooth Skin', category: 'beauty', emoji: '✨', scale: 1, beauty: true, anchor: 'face' },
  { id: 'beauty', name: 'Beauty Filter', category: 'beauty', emoji: '💄', scale: 1, beauty: true, anchor: 'face' },
  { id: 'bgBlur', name: 'Blur room', category: 'backgrounds', emoji: '🌁', scale: 1, background: 'blur' },
  { id: 'bgDim', name: 'Dim studio', category: 'backgrounds', emoji: '🌑', scale: 1, background: 'dim' },
  { id: 'bgSunset', name: 'Sunset', category: 'backgrounds', emoji: '🌇', scale: 1, background: 'sunset' },
  { id: 'bgNight', name: 'Night city', category: 'backgrounds', emoji: '🌃', scale: 1, background: 'night' },
  { id: 'bgStudio', name: 'Soft studio', category: 'backgrounds', emoji: '💡', scale: 1, background: 'studio' },
  { id: 'bgNeon', name: 'Neon club', category: 'backgrounds', emoji: '💜', scale: 1, background: 'neon' },
];

export function getFilterDef(id: FaceFilterId | string | null | undefined): FaceFilterDef | null {
  if (!id || id === 'none') return null;
  return FACE_FILTER_CATALOG.find((f) => f.id === id) ?? null;
}

export function filtersByCategory(category: FaceFilterCategory): FaceFilterDef[] {
  return FACE_FILTER_CATALOG.filter((f) => f.category === category || f.id === 'none');
}
