export const queryKeys = {
  me: ['auth', 'me'] as const,
  badges: ['users', 'badges'] as const,
  users: (params?: Record<string, unknown>) => ['users', 'discover', params] as const,
  discover: (params?: Record<string, unknown>) => ['users', 'discover', params] as const,
  hosts: (params?: Record<string, unknown>) => ['users', 'hosts', params] as const,
  topHosts: ['users', 'hosts', 'top-rated'] as const,
  topRatedHosts: ['users', 'hosts', 'top-rated'] as const,
  popularHosts: ['settings', 'popular-hosts'] as const,
  user: (id: string) => ['users', id] as const,
  profile: ['users', 'me', 'profile'] as const,
  location: ['users', 'me', 'location'] as const,
  matches: ['social', 'matches'] as const,
  likes: ['social', 'likes'] as const,
  following: ['social', 'following'] as const,
  conversations: ['chat', 'conversations'] as const,
  messages: (conversationId: string) => ['chat', 'messages', conversationId] as const,
  wallet: ['wallet'] as const,
  diamondTx: (page?: number) => ['wallet', 'diamonds', page] as const,
  goldTx: (page?: number) => ['wallet', 'gold', page] as const,
  packages: ['payments', 'packages'] as const,
  notifications: ['notifications'] as const,
  notificationsPage: (page?: number) => ['notifications', page] as const,
  liveList: ['live', 'list'] as const,
  liveListPage: (page?: number) => ['live', 'list', page] as const,
  live: ['live', 'list'] as const,
  liveRoom: (id: string) => ['live', id] as const,
  callHistory: ['calls', 'history'] as const,
  callHistoryPage: (page?: number) => ['calls', 'history', page] as const,
  blocked: ['moderation', 'blocks'] as const,
  blocks: ['moderation', 'blocks'] as const,
  settings: ['settings'] as const,
  stats: ['settings', 'stats'] as const,
  reviews: (hostId: string) => ['reviews', hostId] as const,
  gifts: ['gifts'] as const,
  verification: ['verification', 'me'] as const,
  interactions: ['users', 'interactions'] as const,
  contact: ['contact'] as const,
} as const;
