import type { FilterCategory, FilterDefinition } from './types.js';

const ALL = ['web', 'android', 'ios'] as const;
/** Sprite and shader work is live on web; the native engines land separately. */
const WEB_ONLY = ['web'] as const;

export const FILTER_CATEGORY_LABELS: Record<FilterCategory, string> = {
  none: 'None',
  beauty: 'Beauty',
  color: 'Color',
  glasses: 'Glasses',
  animals: 'Animals',
  accessories: 'Accessories',
  fun: 'Fun',
  masks: 'Masks',
  makeup: 'Makeup',
  effects: 'Effects',
};

/**
 * Every entry here is backed by a real shader or a real sprite painter. A
 * category with no implemented filters is deliberately absent rather than
 * present and empty.
 */
export const KUSHLOV_FILTERS: FilterDefinition[] = [
  {
    id: 'none',
    name: 'None',
    category: 'none',
    thumbnail: '✕',
    kind: 'none',
    supportedPlatforms: [...ALL],
  },

  {
    id: 'beautyNatural',
    name: 'Natural',
    category: 'beauty',
    thumbnail: '✨',
    kind: 'beauty',
    beauty: { skinSmoothing: 0.45, brightness: 0.08, warmth: 0.55 },
    supportedPlatforms: [...WEB_ONLY],
  },
  {
    id: 'beautySmooth',
    name: 'Smooth Skin',
    category: 'beauty',
    thumbnail: '🧴',
    kind: 'beauty',
    beauty: { skinSmoothing: 0.75, brightness: 0.12, warmth: 0.52 },
    supportedPlatforms: [...WEB_ONLY],
  },
  {
    id: 'beautyBright',
    name: 'Bright',
    category: 'beauty',
    thumbnail: '💡',
    kind: 'beauty',
    beauty: { skinSmoothing: 0.35, brightness: 0.3, warmth: 0.6 },
    supportedPlatforms: [...WEB_ONLY],
  },

  {
    id: 'colorWarm',
    name: 'Warm',
    category: 'color',
    thumbnail: '🔆',
    kind: 'colorGrade',
    colorGrade: 'warm',
    supportedPlatforms: [...WEB_ONLY],
  },
  {
    id: 'colorCool',
    name: 'Cool',
    category: 'color',
    thumbnail: '❄️',
    kind: 'colorGrade',
    colorGrade: 'cool',
    supportedPlatforms: [...WEB_ONLY],
  },
  {
    id: 'colorVintage',
    name: 'Vintage',
    category: 'color',
    thumbnail: '📷',
    kind: 'colorGrade',
    colorGrade: 'vintage',
    supportedPlatforms: [...WEB_ONLY],
  },
  {
    id: 'colorCinematic',
    name: 'Cinematic',
    category: 'color',
    thumbnail: '🎬',
    kind: 'colorGrade',
    colorGrade: 'cinematic',
    supportedPlatforms: [...WEB_ONLY],
  },
  {
    id: 'colorMono',
    name: 'Mono',
    category: 'color',
    thumbnail: '⚫',
    kind: 'colorGrade',
    colorGrade: 'mono',
    supportedPlatforms: [...WEB_ONLY],
  },

  {
    id: 'glassesClassic',
    name: 'Classic',
    category: 'glasses',
    thumbnail: '🕶️',
    kind: 'faceAccessory',
    sprites: [{ sprite: 'sunglasses', anchor: 'eyes', scale: 1.28 }],
    supportedPlatforms: [...WEB_ONLY],
  },
  {
    id: 'glassesAviator',
    name: 'Aviator',
    category: 'glasses',
    thumbnail: '😎',
    kind: 'faceAccessory',
    sprites: [{ sprite: 'aviator', anchor: 'eyes', scale: 1.32 }],
    supportedPlatforms: [...WEB_ONLY],
  },
  {
    id: 'glassesHeart',
    name: 'Hearts',
    category: 'glasses',
    thumbnail: '😍',
    kind: 'faceAccessory',
    sprites: [{ sprite: 'heartGlasses', anchor: 'eyes', scale: 1.28 }],
    supportedPlatforms: [...WEB_ONLY],
  },
  {
    id: 'glassesRainbow',
    name: 'Rainbow',
    category: 'glasses',
    thumbnail: '🌈',
    kind: 'faceAccessory',
    sprites: [{ sprite: 'rainbowGlasses', anchor: 'eyes', scale: 1.26, yOffset: -0.02 }],
    supportedPlatforms: [...WEB_ONLY],
  },

  {
    id: 'animalDog',
    name: 'Dog',
    category: 'animals',
    thumbnail: '🐶',
    kind: 'faceAccessory',
    sprites: [
      { sprite: 'dogEars', anchor: 'forehead', scale: 1.32, yOffset: -0.04 },
      { sprite: 'dogNose', anchor: 'nose', scale: 0.92 },
    ],
    supportedPlatforms: [...WEB_ONLY],
  },
  {
    id: 'animalCat',
    name: 'Cat',
    category: 'animals',
    thumbnail: '🐱',
    kind: 'faceAccessory',
    sprites: [
      { sprite: 'catEars', anchor: 'forehead', scale: 1.28, yOffset: -0.06 },
      { sprite: 'catNose', anchor: 'nose', scale: 0.85 },
      { sprite: 'catWhiskers', anchor: 'mouth', scale: 1.15, yOffset: -0.08 },
    ],
    supportedPlatforms: [...WEB_ONLY],
  },
  {
    id: 'animalBunny',
    name: 'Bunny',
    category: 'animals',
    thumbnail: '🐰',
    kind: 'faceAccessory',
    sprites: [{ sprite: 'bunnyEars', anchor: 'forehead', scale: 1.35, yOffset: -0.08 }],
    supportedPlatforms: [...WEB_ONLY],
  },

  {
    id: 'accCrown',
    name: 'Crown',
    category: 'accessories',
    thumbnail: '👑',
    kind: 'faceAccessory',
    sprites: [{ sprite: 'crown', anchor: 'forehead', scale: 1.38, yOffset: -0.1 }],
    supportedPlatforms: [...WEB_ONLY],
  },
  {
    id: 'accFlowerCrown',
    name: 'Flowers',
    category: 'accessories',
    thumbnail: '🌸',
    kind: 'faceAccessory',
    sprites: [{ sprite: 'flowerCrown', anchor: 'forehead', scale: 1.4, yOffset: -0.08 }],
    supportedPlatforms: [...WEB_ONLY],
  },
  {
    id: 'accDevilHorns',
    name: 'Horns',
    category: 'accessories',
    thumbnail: '😈',
    kind: 'faceAccessory',
    sprites: [{ sprite: 'devilHorns', anchor: 'forehead', scale: 1.32, yOffset: -0.1 }],
    supportedPlatforms: [...WEB_ONLY],
  },

  {
    id: 'funMustache',
    name: 'Mustache',
    category: 'fun',
    thumbnail: '🥸',
    kind: 'faceAccessory',
    sprites: [{ sprite: 'mustache', anchor: 'mouth', scale: 1.22, yOffset: -0.04 }],
    supportedPlatforms: [...WEB_ONLY],
  },
  {
    id: 'funClownNose',
    name: 'Clown',
    category: 'fun',
    thumbnail: '🤡',
    kind: 'faceAccessory',
    sprites: [{ sprite: 'clownNose', anchor: 'nose', scale: 0.95 }],
    supportedPlatforms: [...WEB_ONLY],
  },
  {
    id: 'funLaserEyes',
    name: 'Lasers',
    category: 'fun',
    thumbnail: '🔴',
    kind: 'faceAccessory',
    sprites: [{ sprite: 'laserEyes', anchor: 'eyes', scale: 1.2, blend: 'screen' }],
    supportedPlatforms: [...WEB_ONLY],
  },
  {
    id: 'funAnimeEyes',
    name: 'Anime',
    category: 'fun',
    thumbnail: '👀',
    kind: 'faceAccessory',
    sprites: [{ sprite: 'animeEyes', anchor: 'eyes', scale: 1.18 }],
    supportedPlatforms: [...WEB_ONLY],
  },

  {
    id: 'maskMedical',
    name: 'Medical',
    category: 'masks',
    thumbnail: '😷',
    kind: 'faceAccessory',
    sprites: [{ sprite: 'medicalMask', anchor: 'mouth', scale: 1.35 }],
    supportedPlatforms: [...WEB_ONLY],
  },
  {
    id: 'maskRobot',
    name: 'Robot',
    category: 'masks',
    thumbnail: '🤖',
    kind: 'faceAccessory',
    sprites: [
      { sprite: 'robotVisor', anchor: 'eyes', scale: 1.2 },
      { sprite: 'robotJaw', anchor: 'mouth', scale: 1.05 },
    ],
    supportedPlatforms: [...WEB_ONLY],
  },
  {
    id: 'maskAnonymous',
    name: 'Anonymous',
    category: 'masks',
    thumbnail: '🎭',
    kind: 'faceAccessory',
    sprites: [{ sprite: 'anonMask', anchor: 'face', scale: 1.18 }],
    supportedPlatforms: [...WEB_ONLY],
  },
];
